### ISSUE TITLE
Move core-utilities/.../corpusreaders files into corpusreaders package

### ISSUE THREAD

**Issue by mayhewsw** [IllinoisCogComp/illinois-cogcomp-nlp#137]
I see no reason why we should have the package `edu.illinois.cs.cogcomp.nlp.corpusreaders` split across the filesystem. There is a dedicated package for corpus readers, and then there is a package underneath core-utilities.

I suggest we move the core-utilities/.../corpusreaders into the corpusreaders package.

**Comment by mssammon** [comment]
The problem is one of dependencies. A number of tests in illinois-cogomp-nlp use basic corpus readers, but those in the corpusreaders package use a range of data structures beyond those in core-utilities.  I'd like to avoid introducing those additional data structures via this dependency.  My intention is that the readers in the corpusreaders package will be modified to use TextAnnotations etc. and then moved to the illinois-cogcomp-nlp project.

**Comment by mayhewsw** [comment]
I'm not sure I understand. The [corpusreaders package](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/tree/master/corpusreaders) I'm referring to is under illinois-cogcomp-nlp. It looks as though files in that package all use standard core-utilities data structures?

For clarity, I want to move [this folder](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/tree/master/core-utilities/src/main/java/edu/illinois/cs/cogcomp/nlp/corpusreaders) into [this folder](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/tree/master/corpusreaders).

**Comment by mayhewsw** [comment]
Oh, I think I understand. Are you referring to the illinois-nlp-readers project in gitlab? I agree -- I don't want to merge that right now.

**Comment by mssammon** [comment]
Right. I don't see any reason to keep the two separate corpus reader packages within illinois-cogcomp-nlp -- @danyaljj, @christos-c do you have any reasons why these shouldn't be combined?

**Comment by christos-c** [comment]
I'm all for combining related packages.

**Comment by mayhewsw** [comment]
Alright then. I'll do it.
