### ISSUE TITLE
Words have multiple Brown cluster representations.

### ISSUE THREAD

**Issue by mliu-dark-knight** [IllinoisCogComp/illinois-cogcomp-nlp#142]
Some of the words have different brown cluster representations. For example, the word "In" have the following representations: prefix-4: 1101, prefix-6: 110101, prefix-10: 1101011110, prefix-4: 1110, prefix-6: 111010.

**Comment by cttsai** [comment]
Where did you see this? What are the relevant files?

**Comment by danyaljj** [comment]
Quote from @christos-c :  
"I think it has to do with the multiple Brown cluster files used by the view generator"

**Comment by mliu-dark-knight** [comment]
Sorry for the late reply. In the wsj treebank for dependency parsing, section 00, wsj_0001.mrg, the first sentence 
1	Pierre	_	NNP	_	_	2	NAME	_	_
2	Vinken	_	NNP	_	_	8	SBJ	_	_
3	,	_	,	_	_	2	P	_	_
4	61	_	CD	_	_	5	NMOD	_	_
5	years	_	NNS	_	_	6	AMOD	_	_
6	old	_	JJ	_	_	2	APPO	_	_
7	,	_	,	_	_	2	P	_	_
8	will	_	MD	_	_	0	ROOT	_	_
9	join	_	VB	_	_	8	VC	_	_
10	the	_	DT	_	_	11	NMOD	_	_
11	board	_	NN	_	_	9	OBJ	_	_
12	as	_	IN	_	_	9	ADV	_	_
13	a	_	DT	_	_	15	NMOD	_	_
14	nonexecutive	_	JJ	_	_	15	NMOD	_	_
15	director	_	NN	_	_	12	PMOD	_	_
16	Nov.	_	NNP	_	_	9	TMP	_	_
17	29	_	CD	_	_	16	NMOD	_	_
18	.	_	.	_	_	8	P	_	_
Word "a" at position 13 has two different 4-bit representation. 1110 and 1000 using instance320 from edison.

**Comment by cttsai** [comment]
When we load clusters, we try to clean up the words. So a token "a/" becomes "a". This creates another representation for "a". How are we going to deal with this? Just remove the rule that removes trailing slashes? I actually don't think we need to modify/normalize the results of brown cluster. But maybe it's important for some application?

**Comment by mssammon** [comment]
If I understand correctly: the code is loading a representation of brown clusters and building a dictionary from word to cluster id.  When it is processing a key/value pair, it perturbs the key and gets more than one value (i.e., it merges several clusters).  Is that right?
If so, I think the correct way to deal with this is to do any normalization when we build the brown clusters and build the dictionary using the keys in the brown cluster file, without manipulating them. @danyaljj @christos-c any reason to do otherwise?

**Comment by cttsai** [comment]
Right. And I agree that the right way is to normalize the input when we train brown clusters. Given that it may be learnt from large amount of text, normalization may not be important. Either way, we shouldn't modify anything in the brown cluster file.
If you all agree with this, I'll remove the normalization part and respect the original key/value pairs.

**Comment by christos-c** [comment]
I also agree, but doesn't this mean we have to retrain the Brown clusters (w/ the preprocessing)?

**Comment by cttsai** [comment]
Yeah, or just use the existing clusters. As far as I know, NER also uses these clusters, but without any normalization. I wonder what will be the impact to other applications.

**Comment by mssammon** [comment]
@cttsai which class(es) did you see this behavior in? -- I'd like to try to find projects using this specific class.

**Comment by cttsai** [comment]
Maybe @mliu-dark-knight can give you the class produces the results he mentioned. 

I simply checked [BrownClusterViewGenerator](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/edison/src/main/java/edu/illinois/cs/cogcomp/edison/annotators/BrownClusterViewGenerator.java) and the brown cluster file. The method loadClusteres() does all the normalization.

**Comment by mssammon** [comment]
@cttsai please separate the normalizing code so that it is optional (configuration flag). If we end up removing it, we will want the documentation of the operations it does so we can reproduce it if necessary.  Please add a test that verifies the correct behavior given the current brown cluster file(s) if the normalization is disabled.  For now, normalization should be active by default.
