### ISSUE TITLE
Revisit ACE Reader

### ISSUE THREAD

**Issue by mssammon** [IllinoisCogComp/illinois-cogcomp-nlp#160]
ACEReader creates a fairly complex TextAnnotation representation over multiple views. It appears that it may make some implicit assumptions about constraints on relations in the source corpus: relation identifiers are stored in argument mentions (as an attribute), which could mean only a single relation per argument can have this information recorded.  Maybe there is a workaround, but I'd like to verify and document it.

**Comment by bhargav** [comment]
Yes. There are a few implementation issues that we should fix to make the Reader simpler:

1. Handling *HEAD* and *EXTENT* for each mention - Right now, we have two different views for mentions - one stores *heads* as constituents and the other one stores *extents* as constituents.  They are both independent views and the only way to reliably map constituents across both views is to use the `EntityMentionID` attribute. 

2. Currently, the `Relation` class that links two constituents does not have support for more attributes. This prevents us from storing *RelationSubType*, *Modality*, *Tense* and other features. Thus, the current workaround is to add new (and potentially duplicate) constituents for each source/target mention. The source mentions is added as a `Predicate` in the Predicate Argument View. Also all relation specific implementation is added to the source mention as attributes.

**Comment by mssammon** [comment]
@bhargav what happens if the same mention is the head of two relations, e.g. "[Professor Roth] works for the University of Illinois and lives in Urbana"?

**Comment by bhargav** [comment]
The PredicateArgumentView would have two different predicates:

- P1 = "[Professor Roth]" predicate with argument as "[University of Illinois]" and the relation specific attributes set inside P1

- P2 = "[Professor Roth]" predicate with argument as "[Urbana]" and the relation specific attributes set inside P2

Since P1 and P2 have different set of attributes, they are treated as different predicates in the PredicateArgumentView. 

Presently, the best way to access all relations would be to get all predicates first and follow their outgoing relations. Each predicate would have a single outgoing relation only. For mentions participating in multiple relations, each relation source would have a separate predicate constituent instance.

**Comment by bhargav** [comment]
Pending Issues with the ACEReader (tracking it here):
- Need to store metadata for each document in the TextAnnotation. [Includes Date/Time, Headline, DocumentID etc]
- The MentionHeadEndCharOffset does not align with character offsets for Token Constituents. Right now the MentionHead attributes are inclusive as [MentionHeadStartCharOffset, MentionHeadEndCharOffset]

**Comment by mssammon** [comment]
I think this is the only remaining issue: 
Pending issues:

Adding attributes to TextAnnotation and have ACEReader populate document metadata. [Will send a separate PR to simplify review]

**Comment by bhargav** [comment]
Closing. All issues fixed. 👍
