### ISSUE TITLE
Pipeline to the superproject

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/illinois-cogcomp-nlp#168]
So the bottleneck for current pipeline is that, Semaphore (or any other reasonable CI) is not able to handle such a big memory needed for the tests. 

One idea that came up the other day while talking with @bhargav is that, we can disable such memory intensive tests in the repo, and instead have scripts on our machine running them (on nightly/weekly basis) on a local server. 
So the pipeline will be moved to the superproject, but it will be tested only on our machines once in a while. 

Clearly this is not the safest option, as one might somehow break something in the pipeline; however I think but that should be mostly fine, as we already have test for many of it's components/annotators. 

What are your thoughts on this?

**Comment by reckart** [comment]
JUnit has a functionality called "Assume" that can be used to skip tests if certain conditions are not given. You could use that to run tests only if sufficient memory is available:

```
	@Test
	public void testEnglish()
		throws Exception
	{
		Assume.assumeTrue(Runtime.getRuntime().maxMemory() > 1000000000);
```

**Comment by christos-c** [comment]
I don't think it's safe to only run memory-intensive tests locally. This would defeat the point of CI for projects like SRL, Coref and Wikifier (since we can't guarantee that the setup in our machines is going to be matching that of machines outside the group). 

It would be better to try and find ways to reduce the footprint for the entire pipeline -- maybe have "pruned"  versions of the models?

**Comment by cowchipkid** [comment]
I am confused as to why Semaphore is not able to run huge memory tests, if the memory is available?

**Comment by mssammon** [comment]
@cowchipkid it is *not* available, as CI is run on Sempahore-owned machines.
