### ISSUE TITLE
Instability of chunker performance in temporal chunking

### ISSUE THREAD

**Issue by qiangning** [IllinoisCogComp/illinois-cogcomp-nlp#214]
One potential issue identified: If in a single run, I train, save .lc and .lex, and then test, BIOTester gives me performance P=77.519, R=72.464, F1=74.906; but later if I test again (now I already have .lc and .lex saved somewhere and I just load them), it gives me performance like this: P=88.393, R=71.739, F1=79.200.

[Example branch](https://github.com/qiangning/illinois-cogcomp-nlp/tree/instability_debug). Run it directly, you will get P=77.519, R=72.464, F1=74.906; If you change this [line](https://github.com/qiangning/illinois-cogcomp-nlp/blob/instability_debug/chunker/src/main/java/edu/illinois/cs/cogcomp/chunker/main/myTester.java#L18) to be false and rerun it, you will get P=88.393, R=71.739, F1=79.200.

**Comment by mssammon** [comment]
This may be do do with the way lbjava initializes its classifiers: @bhargav @danyaljj @shyamupa @cowchipkid FYI.

**Comment by danyaljj** [comment]
>  but later if I test again (now I already have .lc and .lex saved somewhere and I just load them), it gives me performance like this: P=88.393, R=71.739, F1=79.200. 

How about you repeat this multiple times? Does it give different scores each time? 

Also could you print size of lexicon for each run?

**Comment by cowchipkid** [comment]
In NER, we just discovered that the when it trains and reports a final result, those results are wrong, they are the results from the *last model built*, not necessarily the best one (which is the one saved). Perhaps this is the same bug in a different package…

**Comment by qiangning** [comment]
@danyaljj  Repeating it doesn't change the results. Still, if I only test it, P=88.393, R=71.739, F1=79.200; if I retrain and test, P=77.519, R=72.464, F1=74.906.

@cowchipkid I strongly believe this is the same issue. 

How should we fix it then?

**Comment by cowchipkid** [comment]
NER has two disparate features: one was training up a new model, the other was simply testing against a gold standard. 

During training, I use an automatic convergence feature rather than specifying the number of training iterations explicitly. To do this, for training I pass in two disjoint data sets, the larger one to train on, the second is never trained against directly, but is used instead to measure the performance at the end of each iteration and determine when the algorithm has converged sufficiently. During training, we get results at the end of each iteration, and a final result at the end. The final result is essentially useless since that is simply the result for the last model trained *not necessarily the best model*. I completely ignore all these results. However, if testing data is available (this is the third disjoint set then), I go on to read the model that was saved to disk (since the one saved is the best model), and evaluate that model against the testing data. I think this is why we have Test, Dev and Train datasets separated in most of our gold master data. Alternatively, you could do a training run separately, then run again only to test the model against the testing data. This all has to do however with the NER command line interface and how it works, I don’t know if this is the same or comparable to the interface you are using.

**Comment by qiangning** [comment]
Hi Tom, the training scheme with automatic convergence feature is exactly what I need to incorporate in my final pipeline. Now I am just plotting the performance curve against iteration numbers, so I can simply train and test separately.

Before closing this issue, have we already identified which package is causing this inconvenience (i.e., *last model built* instead of the one saved)? Do we need to open an issue for that or do we just live with that?
