### ISSUE TITLE
make a version of NER Gazetteer classes that work with Constituents?

### ISSUE THREAD

**Issue by mssammon** [IllinoisCogComp/illinois-cogcomp-nlp#65]
@cowchipkid : how hard would it be to create a second version of the NER Gazetteer classes that work with Constituents/TextAnnotation instead of NEWords? 
-- There is already a GazetteerViewGenerator in Edison but it has quite different behavior from the NER's current use. 
-- I think the most literal implementation would be to create a SpanLabelView and for each token either: 1) add a constituent for each matching gazetteer at each word position, or 2) add a single constituent with an attribute corresponding to each gazetteer matched at this position
-- alternatively, this class could populate  a SpanLabelView with overlapping multi-token Constituents, where each Constituent corresponds to a complete match of the expression in the TextAnnotation's text.  The caveat here is that I am not sure if this is how the NER uses gazetteer matching.

**Comment by cowchipkid** [comment]
This would not be a difficult thing. Just a lot of refactoring, but there is nothing structurally in the gaz API that relies on NEWord. The general contract is this; given some representation of a term with a way to reference surrounding terms, it will assign a set of features that that term (and surrounding terms where appropriate) that indicate the gazetteer resource the term and surrounding terms matched…

There is one thing that always has concerned me about this and the previous implementation. Because each term simply has an array of gazetteer feature names that individual term matched, there is no mechanism specifically linking phrase matches spanning multiple terms. I don’t know if that matters or not, but I think if we could fabricate a representation that maintains the associated between gazetteer features in adjacent terms so we could easily reconstruct multi-term matches, it would be a better implementation. For this reason, I really like the second representation, this approach would retain this information if I am understanding.

**Comment by mssammon** [comment]
I discussed this with Christos and Daniel and we think that creating a new View with overlapping NER-like constituents (i.e. can cover multiple tokens) is the way to go, as it addresses the multi-term match issue you raise in your comment. Are you able to work on this in the next week or so?

**Comment by cowchipkid** [comment]
Yes, that's it. I can work on it this week. What project would this live in?

**Comment by mssammon** [comment]
In Edison in the illinois-cogcomp-nlp project.  The gazetteers should probably go in 
edu.illinois.cs.cogcomp.edison.features.helpers

while the Annotator should go under
edu.illinois.cs.cogcomp.edison.annotators

-- maybe call it "SimpleGazetteerAnnotator" and have it extend Annotator (the name is to distinguish it from an existing GazetteerViewGenerator, which uses a number of heuristics to filter out some candidates).
If you see a reason to do otherwise, lets discuss it with Christos &/or Daniel.
